import{a as b,S as L,i as w}from"./assets/vendor-95dc692e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const y of r.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&a(y)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S=b.create({baseURL:"https://pixabay.com/api/"});async function f(){const t={key:"43022038-5a6e0a87a795a8bbaa0a62c30",q:l,per_page:m,page:s,image_type:"photo",orientation:"horizontal",safesearch:"true"};return x(),(await S.get("",{params:t})).data}function g(t){if(t.hits.length===0)c("Sorry, there are no images matching your search query. Please try again!");else{const i=t.hits.map(a=>`<li class="gallery-item">
                <a class="gallery-link" href="${a.largeImageURL}">
                <img loading="lazy" class="gallery-image" src="${a.webformatURL}" alt="${a.tags}" />
                </a>
                <div class="stats">
                    <p class="text">Likes<br/>${a.likes}</p>
                    <p class="text">Views<br/>${a.views}</p>
                    <p class="text">Comments<br/>${a.comments}</p>
                    <p class="text">Downloads<br/>${a.downloads}</p>
                </div>
            </li>`).join("");n.gallery.insertAdjacentHTML("beforeend",i),q.refresh()}}const q=new L(".gallery-link",{captionsData:"alt",captionDelay:250}),n={form:document.querySelector(".form"),searchInput:document.getElementById("searchInput"),searchBtn:document.querySelector("button"),loadBtn:document.querySelector(".load-more-button"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};let l="",s=1,m=15,d=0;p();h();n.form.addEventListener("submit",v);async function v(t){if(t.preventDefault(),s=1,n.gallery.innerHTML="",l=n.searchInput.value.trim(),l!=="")try{const o=await f(l,s);d=Math.ceil(o.totalHits/m),g(o),p(),u()}catch(o){console.log(o),c("An error occurred while fetching data.")}else c("Empty field!"),u()}n.loadBtn.addEventListener("click",B);async function B(){s+=1;try{const t=await f(l,s);p(),g(t),d=Math.ceil(t.totalHits/m),u(),s>=d&&c("Sorry, you have reached the end of collection."),requestAnimationFrame(()=>{const i=document.querySelector(".gallery-item").getBoundingClientRect().height;scrollBy({top:i,behavior:"smooth"})})}catch(t){console.log(t),c("An error occurred while fetching data."),u()}}function c(t){w.error({title:"Error",message:t,position:"topRight",backgroundColor:"skyblue"})}function p(){n.loader.style.display="none"}function x(){n.loader.style.display="block"}function u(){s>=d?h():I()}function h(){n.loadBtn.style.display="none"}function I(){n.loadBtn.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
